// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function str(prim) {
  return prim;
}

function Card(Props) {
  var card = Props.card;
  return React.createElement("div", {
              className: "mt-3 flex flex-col"
            }, React.createElement("div", {
                  className: "bg-white mt-3"
                }, React.createElement("img", {
                      className: "border rounded-t-lg shadow-lg ",
                      src: card[/* caption */2]
                    }), React.createElement("div", {
                      className: "bg-white p-1 border shadow flex flex-row flex-wrap"
                    }, React.createElement("div", {
                          className: "w-1/3 hover:bg-gray-200 text-center text-xl text-gray-700 font-semibold"
                        }, "Like"), React.createElement("div", {
                          className: "w-1/3 hover:bg-gray-200 border-l-4 border-r- text-center text-xl text-gray-700 font-semibold"
                        }, "Share"), React.createElement("div", {
                          className: "w-1/3 hover:bg-gray-200 border-l-4 text-center text-xl text-gray-700 font-semibold"
                        }, "Comment")), React.createElement("div", {
                      className: "bg-white border-4 bg-gray-300 border-white rounded-b-lg shadow p-5 text-xl text-gray-700 content-center font-semibold flex flex-row flex-wrap"
                    }, React.createElement("div", {
                          className: "w-full"
                        }, React.createElement("div", {
                              className: "w-full text-left text-xl text-gray-600"
                            }, "@Some Perso"), "A Pretty Cool photo from the mountains. Image credit to @danielmirlea on Unsplash"))));
}

var make = Card;

export {
  str ,
  make ,
  
}
/* react Not a pure module */
