// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as Card$ReasonInstagramClone from "../components/Card.bs.js";

var user = /* record */[
  /* name */"Maxime",
  /* avatar */"http://url.com/avatar"
];

var card1 = /* record */[
  /* id */"uuid1",
  /* user */user,
  /* caption */"https://images.unsplash.com/photo-1572817519612-d8fadd929b00?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80",
  /* created_at */"2019"
];

var card2 = /* record */[
  /* id */"uuid2",
  /* user */user,
  /* caption */"https://images.unsplash.com/photo-1572817519612-d8fadd929b00?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80",
  /* created_at */"2019"
];

var cards_001 = /* :: */[
  card2,
  /* [] */0
];

var cards = /* :: */[
  card1,
  cards_001
];

function Listing(Props) {
  return React.createElement("div", {
              className: "w-full bg-indigo-100 h-screen flex flex-row flex-wrap justify-center "
            }, React.createElement("div", {
                  className: "w-full md:w-3/4 lg:w-4/5 p-5 md:px-12 lg:24 h-full antialiased"
                }, $$Array.of_list(List.map((function (card) {
                            return React.createElement(Card$ReasonInstagramClone.make, {
                                        card: card,
                                        key: card[/* id */0]
                                      });
                          }), cards))));
}

var make = Listing;

var $$default = Listing;

export {
  user ,
  card1 ,
  card2 ,
  cards ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
