// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Card$ReasonInstagramClone from "../components/Card.bs.js";

var user = /* record */[
  /* name */"Maxime",
  /* avatar */"http://url.com/avatar"
];

var card = /* record */[
  /* user */user,
  /* caption */"http://url.com/avatar",
  /* created_at */"2019"
];

function Listing(Props) {
  return React.createElement("div", {
              className: "w-full bg-indigo-100 h-screen flex flex-row flex-wrap justify-center "
            }, React.createElement("div", {
                  className: "w-full md:w-3/4 lg:w-4/5 p-5 md:px-12 lg:24 h-full antialiased"
                }, React.createElement(Card$ReasonInstagramClone.make, {
                      card: card
                    })));
}

var make = Listing;

var $$default = Listing;

export {
  user ,
  card ,
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
